variables:

  - &rust_image "rust:latest"
  - &install_binstall "wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz && tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz && cp cargo-binstall /usr/local/cargo/bin"

services:

  lemmy:
    name: lemmy
    image: dessalines/lemmy:0.19.4-beta.2
    commands:
      - |-
        printf '{
          hostname: lemmy-dev
          database: {
            host: postgres
            password: password
          }
        }' > "$LEMMY_CONFIG_LOCATION"
      # wait for db to start
      - sleep 15
      - lemmy_server
    environment:
      LEMMY_CONFIG_LOCATION: /home/lemmy/config.hjson
    ports:
      - 8536

  postgres:
    name: postgres
    image: postgres:16-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy

steps:

  # lemmy_service_test:
  #   image: quay.io/curl/curl:latest
  #   commands:
  #     # wait for lemmy
  #     - sleep 20
  #     - curl -v http://lemmy:8536/api/v3/site
  #   when:

  cargo_build:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - *install_binstall
      - cargo-binstall -y cargo-leptos
      - apt-get update && apt-get -y install libssl-dev pkg-config
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - . /root/.profile
      - nvm install --lts
      - npm install -g pnpm
      - pnpm install
      - rustup target add wasm32-unknown-unknown
      - cargo leptos build
    when:
      - event: pull_request

  playwright_check:
    # image: quay.io/curl/curl:latest
    # commands:
    #   # wait for lemmy
    #   - sleep 20
    #   # - curl -v http://lemmy:8536/api/v3/site
    when:
      - event: pull_request
    image: *rust_image
    # image: mcr.microsoft.com/playwright:latest
    environment:
      CARGO_HOME: .cargo
    commands:
      - apt update && apt -y install libssl-dev pkg-config  build-essential gcc make

      # - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      # - . "/woodpecker/src/github.com/LemmyNet/lemmy-ui-leptos/.cargo/env"
      # - wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz && tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz && cp cargo-binstall .cargo/bin

      - *install_binstall

      - cargo-binstall -y cargo-leptos

      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - . /root/.profile
      - nvm install --lts

      - npm install -g pnpm
      - pnpm install

      - rustup target add wasm32-unknown-unknown
      - LEMMY_UI_LEPTOS_LEMMY_HOST=lemmy
      - LEMMY_UI_LEPTOS_LEMMY_HTTPS=false
      - LEPTOS_TAILWIND_VERSION=v3.4.1
      - cargo leptos watch &

      - cd end2end
      - pnpm install

      - npx playwright install --with-deps

#      - cd ..
#      - sleep 120
#      - cd end2end
      - npx playwright test

  prettier_check:
    image: tmknom/prettier:3.0.0
    commands:
      - prettier -c .
    when:
      - event: pull_request

  toml_fmt:
    image: tamasfe/taplo:0.8.1
    commands:
      - taplo format --check
    when:
      - event: pull_request

  cargo_fmt:
    image: *rust_image
    environment:
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
    when:
      - event: pull_request

  leptos_fmt:
    image: *rust_image
    commands:
      - *install_binstall
      - cargo binstall -y leptosfmt
      - leptosfmt -c .leptosfmt.toml --check src
    when:
      - event: pull_request

  cargo_machete:
    image: *rust_image
    commands:
      - *install_binstall
      - cargo binstall -y cargo-machete
      - cargo machete
    when:
      - event: pull_request

  cargo_clippy:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - apt-get update && apt-get -y install libssl-dev pkg-config
      - rustup component add clippy
      - cargo clippy
    when:
      - event: pull_request

  # cargo_build:
  #   image: *rust_image
  #   environment:
  #     CARGO_HOME: .cargo
  #   commands:
  #     - *install_binstall
  #     - cargo-binstall -y cargo-leptos
  #     - apt-get update && apt-get -y install libssl-dev pkg-config
  #     - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  #     - . /root/.profile
  #     - nvm install --lts
  #     - npm install -g pnpm
  #     - pnpm install
  #     - rustup target add wasm32-unknown-unknown
  #     - cargo leptos build
  #   when:
  #     - event: pull_request

  # Nothing to test yet
  # cargo_test:
  #   image: *rust_image
  #   environment:
  #     CARGO_HOME: .cargo
  #   commands:
  #     - apt-get update && apt-get -y install libssl-dev pkg-config
  #     - rustup target add wasm32-unknown-unknown
  #     - cargo install cargo-leptos
  #     - cargo leptos test

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy-UI-leptos build failed: ${CI_BUILD_LINK}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: failure

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy-UI-leptos:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag
