variables:
  - &cd_workdir "cd /usr/src/app"

steps:
  prettier_check:
    image: tmknom/prettier:3.2.5
    commands:
      - prettier -c .
    when:
      - event: pull_request

  toml_fmt:
    image: tamasfe/taplo:0.8.1
    commands:
      - taplo format --check
    when:
      - event: pull_request

  cargo_fmt:
    image: rustlang/rust:nightly-bookworm-slim
    commands:
      - rustup component add rustfmt
      - cargo +nightly fmt -- --check
    when:
      - event: pull_request

  cargo_clippy:
    image: rust:slim-bookworm
    commands:
      - rustup component add clippy
      - cargo clippy
    when:
      - event: pull_request

  build_image:
    image: docker:latest
    commands:
      - docker build --rm -t local/base --target base .
      - docker build --rm -t local/leptos-ui --target leptos-ui .
      - docker build --rm -t local/playwright --target playwright .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - event: pull_request

  leptos_fmt:
    image: local/leptos-ui
    commands:
      - *cd_workdir
      - cargo binstall -y leptosfmt
      - leptosfmt -c .leptosfmt.toml --check src
    when:
      - event: pull_request
    depends_on: [build_image]

  cargo_machete:
    image: local/base
    commands:
      - cargo binstall -y cargo-machete
      - cargo machete
    when:
      - event: pull_request
    depends_on: [build_image]

  cargo_leptos_build:
    image: local/leptos-ui
    commands:
      - *cd_workdir
      - cargo leptos build
    when:
      - event: pull_request
    depends_on: [build_image]

  cargo_test:
    image: local/leptos-ui
    entrypoint: [cargo, leptos, test]
    when:
      - event: pull_request

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    detach: true
    when:
      - event: pull_request

  lemmy:
    image: dessalines/lemmy:0.19.4-beta.7
    environment:
      LEMMY_CONFIG_LOCATION: /woodpecker/src/github.com/LemmyNet/lemmy-ui-leptos/end2end/lemmy.hjson
    detach: true
    when:
      - event: pull_request
    depends_on: [postgres]

  playwright_check:
    image: local/playwright
    commands:
      - *cd_workdir
    when:
      - event: pull_request
    depends_on: [lemmy, build_image]

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy-UI-leptos build failed: ${CI_BUILD_LINK}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: failure

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy-UI-leptos:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag
